services:
  web:
    image: ghcr.io/remast/gobuff_realworld_example_app/app:latest
    container_name: web
    hostname: web
    network_mode: host
    #ports:
    #  - "3000:3000"
    depends_on: 
      - db
    environment:
      - "WAIT_HOSTS=127.0.0.1:5432"
      - "DATABASE_HOST=127.0.0.1"

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    network_mode: host
    environment:
      - "POSTGRES_DB=gobuff_realworld_example_app_development"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    #ports: 
    #  - "5432:5432"
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    network_mode: host
    #ports:
    #  - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
