version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
  mongo-seed:
    build:
      context: .
      dockerfile: ./mongo-seed/Dockerfile
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_DB: ${MONGODB_DATABASE_NAME}
      USERNAME: ${MONGODB_USERNAME}
      PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - ./mongo-seed:/mongo-seed
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  mongo:
  redis:
